# Generated by Django 5.2.5 on 2025-09-16 00:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Família',
                'verbose_name_plural': 'Famílias',
            },
        ),
        migrations.CreateModel(
            name='Rota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_rota', models.DateField()),
                ('capacidade_max', models.DecimalField(decimal_places=3, max_digits=10, verbose_name='Capacidade Máxima')),
                ('status', models.CharField(choices=[('PLANEJADA', 'Planejada'), ('EM_EXECUCAO', 'Em execução'), ('CONCLUIDA', 'Concluída')], default='PLANEJADA', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Rota',
                'verbose_name_plural': 'Rotas',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nf', models.IntegerField(verbose_name='Nota Fiscal')),
                ('observacao', models.CharField(blank=True, max_length=100, null=True)),
                ('dtpedido', models.DateField(verbose_name='Data do Pedido')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_logistica', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido',
                'verbose_name_plural': 'Pedidos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('peso', models.DecimalField(decimal_places=3, max_digits=10)),
                ('volume', models.DecimalField(blank=True, decimal_places=3, max_digits=10, null=True)),
                ('ativo', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('familia', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='produtos', to='courses.familia')),
            ],
            options={
                'verbose_name': 'Produto',
                'verbose_name_plural': 'Produtos',
            },
        ),
        migrations.CreateModel(
            name='RotaTrajeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=6, max_digits=10)),
                ('datahora', models.DateTimeField(auto_now_add=True)),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trajetos', to='courses.rota')),
            ],
            options={
                'verbose_name': 'Trajeto da Rota',
                'verbose_name_plural': 'Trajetos das Rotas',
                'ordering': ['rota', 'datahora'],
            },
        ),
        migrations.CreateModel(
            name='ProdutoPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='courses.pedido')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens_pedido', to='courses.produto')),
            ],
            options={
                'verbose_name': 'Item do Pedido',
                'verbose_name_plural': 'Itens dos Pedidos',
                'unique_together': {('produto', 'pedido')},
            },
        ),
        migrations.CreateModel(
            name='RotaPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem_entrega', models.PositiveIntegerField(verbose_name='Ordem de Entrega')),
                ('entregue', models.BooleanField(default=False)),
                ('data_entrega', models.DateTimeField(blank=True, null=True)),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rotas', to='courses.pedido')),
                ('rota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='courses.rota')),
            ],
            options={
                'verbose_name': 'Pedido da Rota',
                'verbose_name_plural': 'Pedidos das Rotas',
                'ordering': ['rota', 'ordem_entrega'],
                'unique_together': {('rota', 'pedido')},
            },
        ),
    ]
